spring:
  application:
    name: recipe-app

  # Configuration Thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# Configuration Firebase (à compléter après création du projet Firebase)
firebase:
  project-id: recipe-app-bda5f
  service-account-key-path: src/main/resources/firebase/service-account-key.json

server:
  port: 8080

# Configuration des logs
logging:
  level:
    com.example.recipeapp: DEBUG
    com.google.cloud: INFO
