spring:
  application:
    name: recipe-app
  
  # Configuration Thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# Configuration Firebase (à compléter après création du projet Firebase)
firebase:
  project-id: # À remplir avec votre project-id Firebase (ex: recipe-app-12345)
  service-account-key-path: src/main/resources/firebase/service-account-key.json

server:
  port: 8080

# Configuration des logs
logging:
  level:
    com.example.recipeapp: DEBUG
    com.google.cloud: INFO
